/** Patient shell layout tokens, shared by the shell and its presentation components. */
import { StyleSheet } from "react-native";
export const patientStyles = StyleSheet.create({
  root: { flex: 1 },
  brand: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    padding: 20,
    borderBottomWidth: 0,
  },
  logo: {
    width: 39,
    height: 39,
    borderRadius: 13,
    backgroundColor: "#236958",
    alignItems: "center",
    justifyContent: "center",
  },
  plus: { color: "#fff", fontSize: 30, lineHeight: 34 },
  brandName: { fontSize: 19, fontWeight: "700" },
  caption: { fontSize: 12, marginTop: 3 },
  content: { padding: 20, paddingBottom: 50, gap: 16 },
  title: {
    fontSize: 32,
    lineHeight: 39,
    fontWeight: "600",
    letterSpacing: -0.7,
  },
  pilot: { fontSize: 10, letterSpacing: 1.6, fontWeight: "700" },
  copy: { fontSize: 15, lineHeight: 23, marginVertical: 3 },
  card: { borderWidth: 1, borderRadius: 18, padding: 18, gap: 8 },
  cardTitle: { fontSize: 19, fontWeight: "600", marginBottom: 4 },
  label: { fontSize: 14, fontWeight: "600", marginTop: 6 },
  input: {
    borderWidth: 1,
    borderRadius: 10,
    padding: 13,
    fontSize: 16,
    minHeight: 48,
  },
  button: {
    padding: 14,
    borderRadius: 11,
    borderWidth: 1,
    alignItems: "center",
    marginTop: 6,
    minHeight: 48,
  },
  buttonText: { fontSize: 15, fontWeight: "700" },
  error: {
    color: "#b7402d",
    backgroundColor: "#fff0e9",
    padding: 14,
    borderRadius: 10,
    fontSize: 15,
  },
  tabs: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
  tab: {
    paddingHorizontal: 15,
    paddingVertical: 14,
    borderWidth: 1,
    borderRadius: 25,
    minHeight: 44,
  },
  passport: {
    backgroundColor: "#174f45",
    borderRadius: 20,
    padding: 25,
    gap: 14,
  },
  passportLabel: {
    color: "#bde5d6",
    fontSize: 10,
    fontWeight: "700",
    letterSpacing: 1.7,
  },
  passportName: { color: "#fff", fontSize: 26, fontWeight: "600" },
  healthId: {
    color: "#fff",
    fontSize: 15,
    fontWeight: "500",
    letterSpacing: 1,
  },
  passportNote: { color: "#c1dacf", fontSize: 12, lineHeight: 19 },
  row: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 16,
    minHeight: 48,
  },
  footer: { textAlign: "center", fontSize: 12, marginTop: 20 },
  center: { flex: 1, alignItems: "center", justifyContent: "center" },
});
