ALTER TABLE app_user ADD COLUMN clinic VARCHAR(100);
ALTER TABLE app_user ADD COLUMN department VARCHAR(100);
ALTER TABLE app_user ADD COLUMN staff_active BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE app_user ADD COLUMN staff_version INTEGER NOT NULL DEFAULT 0;
ALTER TABLE clinical_record ADD COLUMN observed_at VARCHAR(40);
ALTER TABLE clinical_record ADD COLUMN observed_timezone VARCHAR(80);
ALTER TABLE clinical_record ADD COLUMN updated_at VARCHAR(40);
ALTER TABLE clinical_record ADD COLUMN author_role VARCHAR(20);
ALTER TABLE clinical_record ADD COLUMN author_organization VARCHAR(100);
ALTER TABLE clinical_record ADD COLUMN author_clinic VARCHAR(100);
ALTER TABLE clinical_record ADD COLUMN author_department VARCHAR(100);
ALTER TABLE clinical_record ADD COLUMN source_type VARCHAR(40);
ALTER TABLE clinical_record ADD COLUMN original_record_id VARCHAR(36) REFERENCES clinical_record(id);
ALTER TABLE clinical_record ADD COLUMN historical BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE clinical_record ADD COLUMN record_version INTEGER NOT NULL DEFAULT 0;
ALTER TABLE clinical_record ADD COLUMN note_state VARCHAR(20) NOT NULL DEFAULT 'legacy';
ALTER TABLE clinical_record ADD COLUMN signed_at VARCHAR(40);
ALTER TABLE clinical_record ADD COLUMN encounter_id VARCHAR(36) REFERENCES appointment(id);
ALTER TABLE clinical_record ADD COLUMN correction_reason VARCHAR(1000);
CREATE TABLE record_revision(id VARCHAR(36) PRIMARY KEY, record_id VARCHAR(36) NOT NULL REFERENCES clinical_record(id), actor_id VARCHAR(36) REFERENCES app_user(id), occurred_at VARCHAR(40) NOT NULL, action VARCHAR(40) NOT NULL, reason VARCHAR(1000), previous_value TEXT, new_value TEXT NOT NULL);
CREATE INDEX revision_record ON record_revision(record_id,occurred_at);
CREATE TABLE record_confirmation(id VARCHAR(36) PRIMARY KEY, record_id VARCHAR(36) NOT NULL REFERENCES clinical_record(id), actor_id VARCHAR(36) NOT NULL REFERENCES app_user(id), confirmed_at VARCHAR(40) NOT NULL, comment VARCHAR(1000) NOT NULL);
CREATE TABLE freshness_rule(kind VARCHAR(40) PRIMARY KEY, minutes INTEGER NOT NULL CHECK(minutes>0), version INTEGER NOT NULL DEFAULT 0, updated_by VARCHAR(36) REFERENCES app_user(id), updated_at VARCHAR(40));
INSERT INTO freshness_rule(kind,minutes) VALUES('vital',1440),('history',129600),('allergy',43200),('medication',43200),('condition',129600),('lab_result',43200),('imaging_report',43200),('note',10080),('encounter',10080),('nursing_observation',1440);
CREATE TABLE care_assignment(id VARCHAR(36) PRIMARY KEY, patient_id VARCHAR(36) NOT NULL REFERENCES app_user(id), staff_id VARCHAR(36) NOT NULL REFERENCES app_user(id), organization VARCHAR(100) NOT NULL, clinic VARCHAR(100) NOT NULL, scopes VARCHAR(600) NOT NULL, expires_at VARCHAR(40) NOT NULL, active BOOLEAN NOT NULL DEFAULT TRUE, version INTEGER NOT NULL DEFAULT 0, assigned_by VARCHAR(36) NOT NULL REFERENCES app_user(id), created_at VARCHAR(40) NOT NULL, UNIQUE(patient_id,staff_id));
ALTER TABLE appointment ADD COLUMN workflow_stage VARCHAR(30) NOT NULL DEFAULT 'registered';
CREATE TABLE care_task(id VARCHAR(36) PRIMARY KEY, organization VARCHAR(100) NOT NULL, clinic VARCHAR(100) NOT NULL, patient_id VARCHAR(36) REFERENCES app_user(id), encounter_id VARCHAR(36) REFERENCES appointment(id), scope VARCHAR(40) NOT NULL, title VARCHAR(200) NOT NULL, details TEXT NOT NULL, creator_id VARCHAR(36) NOT NULL REFERENCES app_user(id), assignee_id VARCHAR(36) REFERENCES app_user(id), team VARCHAR(100), priority VARCHAR(20) NOT NULL, due_at VARCHAR(40), acknowledge_by VARCHAR(40), status VARCHAR(20) NOT NULL, version INTEGER NOT NULL DEFAULT 0, request_key VARCHAR(100) NOT NULL, created_at VARCHAR(40) NOT NULL, updated_at VARCHAR(40) NOT NULL, UNIQUE(creator_id,request_key));
CREATE TABLE care_conversation(id VARCHAR(36) PRIMARY KEY, organization VARCHAR(100) NOT NULL, clinic VARCHAR(100) NOT NULL, patient_id VARCHAR(36) REFERENCES app_user(id), encounter_id VARCHAR(36) REFERENCES appointment(id), scope VARCHAR(40) NOT NULL, kind VARCHAR(30) NOT NULL, title VARCHAR(200) NOT NULL, creator_id VARCHAR(36) NOT NULL REFERENCES app_user(id), created_at VARCHAR(40) NOT NULL);
CREATE TABLE conversation_member(conversation_id VARCHAR(36) NOT NULL REFERENCES care_conversation(id), user_id VARCHAR(36) NOT NULL REFERENCES app_user(id), read_at VARCHAR(40), PRIMARY KEY(conversation_id,user_id));
CREATE TABLE care_message(id VARCHAR(36) PRIMARY KEY, conversation_id VARCHAR(36) REFERENCES care_conversation(id), task_id VARCHAR(36) REFERENCES care_task(id), author_id VARCHAR(36) NOT NULL REFERENCES app_user(id), body TEXT NOT NULL, mentions VARCHAR(2000) NOT NULL, attachments VARCHAR(2000) NOT NULL, created_at VARCHAR(40) NOT NULL, request_key VARCHAR(100) NOT NULL, UNIQUE(author_id,request_key));
CREATE TABLE care_event(id VARCHAR(36) PRIMARY KEY, resource_type VARCHAR(30) NOT NULL, resource_id VARCHAR(36) NOT NULL, actor_id VARCHAR(36) NOT NULL REFERENCES app_user(id), occurred_at VARCHAR(40) NOT NULL, action VARCHAR(40) NOT NULL, previous_value TEXT, new_value TEXT NOT NULL);
CREATE TABLE result_review(record_id VARCHAR(36) PRIMARY KEY REFERENCES clinical_record(id), reviewer_id VARCHAR(36) NOT NULL REFERENCES app_user(id), reviewed_at VARCHAR(40) NOT NULL, comment VARCHAR(1000) NOT NULL);
CREATE TABLE service_status(record_id VARCHAR(36) PRIMARY KEY REFERENCES clinical_record(id), status VARCHAR(30) NOT NULL, version INTEGER NOT NULL DEFAULT 0, updated_at VARCHAR(40) NOT NULL, updated_by VARCHAR(36) NOT NULL REFERENCES app_user(id));
